hw_info:
  cpu_id: ""
  cpu_name: e906fp
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: ../board/gcc_flash_1732.ld
  flash_program: ""
def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 1024
  IS_CHIP_1732: 1
name: apt32f173x
version: v1.0.2
description: 我的第一个方案工程
tag: ""
keywords: 
author:
  name: ""
license: ""
type: solution
depends:
  - apt32f173x_demo: v1.0.1
  - sdk_173x: v1.0.2
build_config:
  include:
    - include
    - ./
    - ../components/components/demo/csi_kernel/include/
    - ../components/components/demo/csi_kernel/freertosv10.3.1/include/
    - ../components/components/demo/csi_kernel/freertosv10.3.1/FreeRTOS/Source/include/
    - ../components/components/demo/csi_kernel/freertosv10.3.1/FreeRTOS/Source/portable/GCC/riscv/
    - ../components/components/demo/csi_kernel/freertosv10.3.1/FreeRTOS/Source/portable/GCC/riscv/chip_specific_extensions/thead_rv32/
  internal_include: 
  cflag: -O1  -g1
  cxxflag: -O1  -g1
  asmflag: -Wa,--gdwarf2
  define: 
  libs:
    - libcsi_xt900p32f_dsp.a
  libpath:
    - ../components/csi/dsp/lib/
source_file:
  - src/main.c
  - src/user_demo.c
depends_forward:
  - apt32f173x_demo: v1.0.1
  - sdk_173x: v1.0.2
install: 
homepage: 