hw_info:
  cpu_id: ""
  cpu_name: e906fp
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: ""
  flash_program: ""
def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 1024
  DBG_PRINT2PC: 1
  IS_CHIP_1732: 1
name: apt32f173x
version: v1.2.0
description: 我的第一个方案工程
tag: ""
keywords: 
author:
  name: ""
license: ""
type: solution
depends:
  - apt32f173x_demo: v1.2.0
  - apt32f173x_demo_callback: v1.2.0
  - sdk_173x: v1.2.0
build_config:
  include:
    - include
    - ./
  internal_include: 
  cflag: -Og   -Wall  -ffunction-sections
  cxxflag: -Og   -Wall  -ffunction-sections
  asmflag: -Wa,-gdwarf-2
  define: 
  libs: 
  libpath: 
source_file:
  - src/main.c
  - src/interrupt.c
  - src/user_demo.c
depends_forward:
  - apt32f173x_demo: v1.2.0
  - apt32f173x_demo_callback: v1.2.0
  - sdk_173x: v1.2.0
install: 
homepage: 