hw_info:
  cpu_id: ""
  cpu_name: e906fp
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: link/gcc_flash_1732.ld
  flash_program: ""
def_config:
  CONFIG_ARCH_INTERRUPTSTACK: 1024
  DBG_PRINT2PC: 1
  IS_CHIP_1732: 1
name: apt32f173x
version: v1.2.1
description: 我的第一个方案工程
tag: ""
keywords: 
author:
  name: ""
license: ""
type: solution
depends:
  - apt32f173x_demo: v1.2.1
  - apt32f173x_demo_callback: v1.2.1
  - sdk_173x: v1.2.1
build_config:
  include:
    - ./
  internal_include: 
  cflag: -Og   -Wall  -ffunction-sections
  cxxflag: -Og   -Wall  -ffunction-sections
  asmflag: -Wa,-gdwarf-2
  define: 
  libs: 
  libpath: 
source_file:
  - src/main.c
  - src/user_demo.c
  - src/interrupt.c
  - link_file/gcc_flash_1731.ld
  - link_file/gcc_flash_1732.ld
  - link_file/gcc_flash_dram16k_iram16k_1732.ld
  - link_file/gcc_flash_dram24k_iram8k_1732.ld
depends_forward:
  - apt32f173x_demo: v1.2.1
  - apt32f173x_demo_callback: v1.2.1
  - sdk_173x: v1.2.1
install: 
homepage: 